index:
    path: /
    methods: [GET]
    controller: App\Controller\MainController::getGalery

element:
    path: element/
    methods: [GET]
    controller: App\Controller\ElementController::getElements
    