index:
    path: /
    methods: [GET]
    controller: App\Controller\MainController::getUpdate

element:
    path: v1/element/
    methods: [GET]
    controller: App\Controller\ElementController::getElements
    
element_photos:
    path: v1/element/photos/{id}
    methods: [GET]
    controller: App\Controller\ElementController::getElementPhotos

galery:
    path: galery/
    methods: [GET]
    controller: App\Controller\GalleryController::listGallery

browse_galery:
    path: galery/{id}
    methods: [GET]
    controller: App\Controller\GalleryController::listBrowseGallery

index_em:
    path: em/
    methods: [GET]
    controller: App\Controller\MainController::em
